# Generated by Django 3.2.18 on 2023-07-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='date_Year',
            field=models.CharField(default='YYYY', max_length=5),
        ),
        migrations.AddField(
            model_name='post',
            name='date_day',
            field=models.CharField(default='D', max_length=3),
        ),
        migrations.AddField(
            model_name='post',
            name='date_month',
            field=models.CharField(default='M', max_length=3),
        ),
    ]
