# Generated by Django 4.2.3 on 2023-07-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20230708_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='image_src',
            field=models.URLField(default=None),
        ),
    ]
