# Generated by Django 4.2.3 on 2023-07-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_rename_date_year_post_date_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_added',
        ),
    ]
