# Generated by Django 4.2.3 on 2023-07-09 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_remove_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 7, 24, 48, 851674)),
        ),
    ]
