# Generated by Django 4.2.5 on 2023-09-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_castcrew_productioncountries_item_imdb_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castcrew',
            name='cast_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='castcrew',
            name='gender',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='castcrew',
            name='job',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='castcrew',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='castcrew',
            name='profile_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='movie_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productioncountries',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
