# Generated by Django 4.2.5 on 2023-09-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_castcrew_cast_id_alter_castcrew_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='item',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='item',
            name='production_countries',
        ),
    ]
