# Generated by Django 4.2.5 on 2023-09-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_cast_item_genre_item_production_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='item',
            name='production_countries',
        ),
        migrations.DeleteModel(
            name='CastCrew',
        ),
        migrations.DeleteModel(
            name='ProductionCountries',
        ),
    ]
