# Generated by Django 4.2.3 on 2023-07-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_post_date_added_post_image_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_Year',
            new_name='date_year',
        ),
    ]
