# Generated by Django 4.2.2 on 2023-06-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='download',
            field=models.URLField(),
        ),
    ]
