# Generated by Django 4.2.4 on 2023-08-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_product_productdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDB',
        ),
    ]
