FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install -r requirements.txt

COPY . /app/

# Command to Run Celery Beat and Worker
CMD ["celery", "-A", "your_project_name", "worker", "--loglevel=info", "--concurrency=4", "--beat"]